theme: jekyll-theme-minimal
deploy:
    type: git
    repository: https://github.com/isfull/isfull.github.io.git
    branch: master
    title: Mohosojo
    description: record what I learn, make knowledge simple


# https://github.com/pages-themes
