theme: jekyll-theme-minimal
deploy:
    type: git
    repository: https://github.com/isfull/isfull.github.io.git
    branch: master
title: Mohosojo
description: record what I learned. make knowledge simple
logo: https://avatars3.githubusercontent.com/u/1584029?s=460&v=4
    
# https://github.com/pages-themes
